### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by LipeApp** [Mirmuxsin/laragram#16]
Problem 1
    - Root composer.json requires milly/laragram 2.2.0.2 -> satisfiable by milly/laragram[2.2.0.2].
    - milly/laragram 2.2.0.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9
.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

Laravel 10 ga ko'tarasizmi?

**Comment by Mirmuxsin** [comment]
Now it supports laravel 10
