### ISSUE TITLE
How to get or read messages send by user?

### ISSUE THREAD

**Issue by yogeshgalav** [Mirmuxsin/laragram#23]
I cannot find method or way from which I can get messages send by user in chat or group?
Is it even possible?
if yes can you provide me an example?

**Comment by Mirmuxsin** [comment]
write any route which accepts webhooks from telegram. For example, lets create route 'bot' inside api.php and use FSM:

```php
use Milly\Laragram\FSM\FSM;

Route::post('/bot', function () {
    FSM::route('', function (Message $message) {
        Laragram::sendMessage(
            $message->chat->id,
            null,
            "Your message is: ".$message->text;
        );
    });
}
```

set your telegram bot webhook to yoursite.com/api/bot and thats it. Bot will reply you with message that you sent

**Comment by Mirmuxsin** [comment]
I'm closing this issue. If you have any other questions, feel free to ask
