### ISSUE TITLE
[feature] Integration with Business Methods

### ISSUE THREAD

**Issue by miztizm** [Mirmuxsin/laragram#24]
Can you please add new business methods to the package? Thank you very much.

March 31, 2024
Bot API 7.2

Integration with Business Accounts

Added the class [BusinessConnection](https://core.telegram.org/bots/api#businessconnection) and updates about the connection or disconnection of the bot to a business account, represented by the field business_connection in the class [Update](https://core.telegram.org/bots/api#update).
Added updates about new messages in a business account connected to the bot, represented by the field business_message in the class [Update](https://core.telegram.org/bots/api#update).
Added updates about message edits in a business account connected to the bot, represented by the field edited_business_message in the class [Update](https://core.telegram.org/bots/api#update).
Added updates about message deletion in a business account connected to the bot, represented by the class [BusinessMessagesDeleted](https://core.telegram.org/bots/api#businessmessagesdeleted) and the field deleted_business_messages in the class [Update](https://core.telegram.org/bots/api#update).
Added the method [getBusinessConnection](https://core.telegram.org/bots/api#getbusinessconnection).
Working on Behalf of Business Accounts

Added the parameter business_connection_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
Added the parameter business_connection_id to the method [sendChatAction](https://core.telegram.org/bots/api#sendchataction).
Added the field business_connection_id to the class [Message](https://core.telegram.org/bots/api#message).
Added the field sender_business_bot to the class [Message](https://core.telegram.org/bots/api#message).
Information about Business Accounts

Added the class [BusinessIntro](https://core.telegram.org/bots/api#businessintro) and the field business_intro to the class [Chat](https://core.telegram.org/bots/api#chat).
Added the class [BusinessLocation](https://core.telegram.org/bots/api#businesslocation) and the field business_location to the class [Chat](https://core.telegram.org/bots/api#chat).
Added the classes [BusinessOpeningHours](https://core.telegram.org/bots/api#businessopeninghours) and [BusinessOpeningHoursInterval](https://core.telegram.org/bots/api#businessopeninghoursinterval) and the field business_opening_hours to the class [Chat](https://core.telegram.org/bots/api#chat).

**Comment by Mirmuxsin** [comment]
Thank you for request

Added in 3.2.1 
https://github.com/Mirmuxsin/laragram/releases/tag/3.2.1
